export const ActionTypes = {
  DISPLAY_PRODUCTS: "DISPLAY_PRODUCTS",
  SELECT_PRODUCT: "SELECT_PRODUCT",
  FILTER_PRODUCT: "FILTER_PRODUCT",
  REMOVE_FILTER_PRODUCT: "REMOVEFILTER_PRODUCT",
  REMOVE_PRODUCT_DETAILS: "REMOVE_PRODUCT_DETAILS",
  ADDTOCART: "ADDTOCART",
  REMOVEFROMCART: "REMOVEFROMCART",
};
